# Generated by Django 4.2 on 2025-05-03 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_rename_is_banned_user_is_admin_only_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='CorporationCheckSettings',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='ship_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='position',
            name='department',
        ),
        migrations.RemoveField(
            model_name='position',
            name='description',
        ),
        migrations.RemoveField(
            model_name='position',
            name='function',
        ),
        migrations.RemoveField(
            model_name='position',
            name='image',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='source',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='department',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='image',
        ),
        migrations.RemoveField(
            model_name='role',
            name='department',
        ),
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.RemoveField(
            model_name='role',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='ship_description',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='ship_image',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='user',
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='verificationstatus',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='verificationstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Function',
        ),
    ]
